### ISSUE TITLE
Wrong library_path in lvp_icd.x86_64.json

### ISSUE THREAD

**Issue by StefanG3D** [mmozeiko/build-mesa#1]
Absolute path in mesa-lavapipe-*.zip would only work on the computer it had been built on
_"library_path": "D:\\a\\build-mesa\\build-mesa\\mesa-llvmpipe\\bin\\vulkan_lvp.dll"_

It should be:
_"library_path": ".\\vulkan_lvp.dll"_

**Comment by StefanG3D** [comment]
Almost there in the new archive, this forum ate a backslash.
Windows insists on a dot and 2 backslashes
`"library_path": ".\\vulkan_lvp.dll"`

Also i added a batch file in the same folder with following content:
`setx /m VK_ADD_DRIVER_FILES %~dp0\lvp_icd.x86_64.json`

**Comment by mmozeiko** [comment]
Hmm, I tried to run with `set VK_ICD_FILENAMES=lvp_icd.x86_64.json` (with just `"library_path": "vulkan_lvp.dll"` inside) and vkcube.exe was running using `vulkan_lvp.dll` file. The `VK_ADD_DRIVER_FILES` variable did not work for me regardless of json content - relative path or absolute path.

**Comment by StefanG3D** [comment]
I'm not sure why my system is picky with the library_path

Looks like there is VK_ADD_DRIVER_FILES and VK_DRIVER_FILES which is equal to VK_ICD_FILENAMES according to 
https://vulkan.lunarg.com/doc/view/1.3.211.0/linux/LoaderDriverInterface.html#user-content-overriding-the-default-driver-discovery
I think i have to check if misc. apps prefer a particular method...
