### ISSUE TITLE
Build artifacts for Windows on Arm

### ISSUE THREAD

**Issue by tim-rex** [mmozeiko/build-mesa#6]
I'm not particularly familiar with github actions, but it looks like arm64 runners for Windows are on the way

Ref: https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/

As such, this is very much a premature request.. but it would be great to produce arm64 releases when that becomes a possibility. I've not tried building myself, but the x64 release serves me quite well (and, quite genuinely.. thank you for putting this repo + releases together, it's incredibly helpful)

**Comment by mmozeiko** [comment]
I believe everything should build for arm64 just fine. But I have not tried it myself. Main reason I have not tried it is that I won't be able to verify that result works, still waiting when new Snapdragon dev kit will be available. I don't really need arm64 runners on github to build this. MSVC provides compiler for x64 host that can do the arm64 target build. It's just a question of passing correct arguments to `vcvarsall.bat` or `cmake` cmmands. I could try doing that a bit later when I'll have time.

**Comment by tim-rex** [comment]
Oh, that's great!
I was going to have a go at building it myself, but I realise I'm additionally blocked on a lack of an arm64 vulkan runtime so no great rush really

**Comment by mmozeiko** [comment]
I've updated the code to build arm64 binaries. Latest release now has both x64 & arm64 binaries.

**Comment by tim-rex** [comment]
That's amazing, nice work.
Can confirm this is working as expected

For reference, I'm running Windows on Arm under Parallels on MacOS

There is no arm64 distribution of the Vulkan SDK, but you can find an arm64 build of the Vulkan Runtime [here](https://packages.msys2.org/package/mingw-w64-clang-aarch64-vulkan-loader?repo=clangarm64)

I've also needed to disable validation layers (again, no sdk availability - yet)

Aside from that, I'm golden here. Thanks again!
