### ISSUE TITLE
softpipe OpenGL driver missing by intention from the releases?

### ISSUE THREAD

**Issue by LowLevelMahn** [mmozeiko/build-mesa#7]
im mean the non LLVM jit based pure software rasterizer

**Comment by LowLevelMahn** [comment]
found it, removed since 21.0

**Comment by mmozeiko** [comment]
Softpipe is pretty obsolete for any real use case. You really do not want to use it - it is much much slower than llvmpipe and offers way less features. I believe it was stuck on 3.3 version, while llvmpipe nowadays goes up to 4.5.

**Comment by LowLevelMahn** [comment]
thanks for the info
